language: node_js
node_js: lts/*
sudo: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
- export PATH=$HOME/.yarn/bin:$PATH
cache: yarn
notifications:
  email:
    on_success: never
    on_failure: always
install:
- yarn install
script:
- yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "KNNWar++pqsYBDi+YSupmDTrB6x8a4HwKZjz7RkDfb08b4o/gfe/lCLeYzAEM631bodpgtDKUusE+OMq7I9wkJMs3nMxGT2k+9eJs/m8ECyRG+6YeQWgL5+uMXJCEA1pu4AuK3LtufXEsAmPh5VrROtkGoPlLdZRENSGTJWF8u1AHISuROimPwkpJKh63yGVaLSVxto7QXVxcJ7dcf/q2aBlg8OUQN2kyVHhFxjdhQo9c7VV1r3E7ptNjYQNvgLmWOBoNhCaHNDXSi2mNSUC+L7GeF2ioCCNDkLFns2Mkx/DXJzfSMnjENBJtNFNewE7dSubk4D1qVV8cb89yaZ+MS/8YWJW7v81uQo6DSKQSSOpsBavi/P69ERE2CX1tU+FTbbw9125KNh4ONTXk1ozMHvMuHPxtQANAu6NxaxC4tp5fICbxqFZaK3eMzzF48xQ7A6/TdxrkfOEu6I47UjgCCAwOQB93jbL07J0asXkv5OC9sJKHTGLIhWuHGqb8ttu7RJbS+A3U+ocMMZX4TAon2DVE1aMxwPHv6eZ+9dFWybNuLPxI6pbdglZgwa6WW4hMH1y39eYw0E2QredyxLU9GvwCdQ2sMPjcVHqDyD5uuUAHXayX0SYRgW/PsfFlmCRbGfqq9c/3sx1Oz0XEIm0a4RgFVO8j16kku4Ci6/FTQc="
