# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Install dependencies
      - run: yarn install
      
      # Cache dependencies
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run build
      - run: yarn build

      # persist to workspace
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build/
            - firebase.json
            - .firebaserc
      
      # store artifact
      - store_artifacts:
          path: build
          destination: build
  
  deploy:
    docker:
      - image: circleci/node:latest

    working_directory: ~/

    steps:
      - attach_workspace:
          at: ~/
      
      - run:
          name: install firebase
          command: |
            npm install --save-dev firebase-tools
      
      - run:
          name: deploy
          command: |
            ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
          
workflows:
  version: 2

  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            only:
              - master

